<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>shader</string>
	</array>
	<key>name</key>
	<string>Unity Shader</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(Sub)?Shader|Category|SeparateSpecular|Fog|Material|ColorMaterial|Name|Properties|CGINCLUDE|FallBack|Tags|LOD|Cull|Blend|AlphaTest|ColorMask|Lighting|ZWrite|BindChannels|Pass|return</string>
			<key>name</key>
			<string>keyword.source.shader</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.source.shader</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>(?&lt;=[, \s\(\)])(((float|half|fixed)[2-4]?)|SurfaceOutput|inout|bool|sampler(CUBE|[23]D)|void|2D|Color|struct|[Ff]loat)(?=[,\s\(\)])</string>
			<key>name</key>
			<string>storage.type.source.shader</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>\"[^\"]*\"</string>
			<key>name</key>
			<string>string.quoted.double.source.shader</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.source.shader</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.preprocessor.source.shader</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>compiler directive</string>
			<key>match</key>
			<string>(#)(pragma|include|ifdef|endif|if|define).*</string>
			<key>name</key>
			<string>meta.preprocessor.source.shader</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>functions</string>
			<key>match</key>
			<string>(length|cross|pow|tex2D|UnpackNormal|saturate|dot|normalize|clip|frac|mul|TRANSFORM_TEX|Bind|SetTexture|matrix|constantColor|combine|UnityPixelSnap)</string>
			<key>name</key>
			<string>support.function.any-method.shader</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>number literals</string>
			<key>match</key>
			<string>\b([-+]?([0-9]+(\.[0-9]+)?|\.[0-9]+)[\s]*,[\s]*)*([-+]?([0-9]+(\.[0-9]+)?|\.[0-9]+)[fF]?)+\b</string>
			<key>name</key>
			<string>constant.numeric.source.shader</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(CGPROGRAM)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.shader</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>CGPROGRAM -- ENDCG</string>
			<key>end</key>
			<string>(ENDCG)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.shader</string>
				</dict>
			</dict>
			<key>name</key>
			<string>cgprogram.source.shader</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shader</string>
	<key>uuid</key>
	<string>e3872ec7-60d7-4cc2-bf8f-57da56c339f2</string>
</dict>
</plist>
